openapi: 3.1.1
info:
  title: Shopify Merchant Analysis Tools
  description: API tools for analyzing merchants, verifying Shopify usage, and finding similar merchants in specific verticals
  version: 1.0.0
  contact:
    name: Shopify Merchant Analysis Agent
    description: Tools for comprehensive merchant analysis and Shopify verification

servers:
  - url: https://httpbin.org
    description: Mock server for testing (replace with actual API server)

paths:
  /post:
    post:
      operationId: searchMerchantsByVertical
      summary: Search for merchants in a specific vertical or segment
      description: Find merchants similar to a given merchant based on vertical, industry, or business segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - vertical
              properties:
                vertical:
                  type: string
                  description: The business vertical or industry segment to search within
                  examples: ["fashion", "home-decor", "electronics", "beauty", "sports"]
                keywords:
                  type: array
                  items:
                    type: string
                  description: Additional keywords to refine the search
                size_filter:
                  type: string
                  enum: ["enterprise", "large", "medium", "small", "all"]
                  default: "all"
                  description: Filter merchants by business size
                limit:
                  type: integer
                  minimum: 1
                  maximum: 50
                  default: 20
                  description: Maximum number of merchants to return
      responses:
        '200':
          description: List of merchants found in the specified vertical
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchants:
                    type: array
                    items:
                      $ref: '#/components/schemas/MerchantInfo'
                  total_found:
                    type: integer
                    description: Total number of merchants found

components:
  schemas:
    MerchantInfo:
      type: object
      required:
        - name
        - website
      properties:
        name:
          type: string
          description: Official merchant name
        website:
          type: string
          format: uri
          description: Primary website URL
        vertical:
          type: string
          description: Business vertical or industry
        estimated_size:
          type: string
          enum: ["enterprise", "large", "medium", "small", "unknown"]
        shopify_status:
          type: string
          enum: ["verified", "inferred", "unknown", "non_shopify"]
        verification_source:
          type: string
          format: uri
          description: Source URL for verification
        shopify_pos:
          type: boolean
          description: Whether merchant uses Shopify POS

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for merchant analysis tools

security:
  - ApiKeyAuth: []